---
- include_vars: "vars/all.yml"
- include_vars: "roles/apprunbot/vars/main.yml"
- include_vars: "vars/protected.yml"
- name: Clone Repo Apprun
  become: yes
  git:
    repo: "{{ git_repo_apprun }}"
    dest: "{{ repo_location_apprun }}"
    accept_hostkey: yes
    depth: 1
    force: yes
    key_file: "{{ git_key_file }}"
- name: Set permissions in Apprun
  become: yes
  file:
    mode: "0770"
    path: "{{ repo_location_apprun }}"
    group: "{{ repo_group }}"
    owner: "{{ bot_user_hockeybot }}"
    recurse: yes
- name: Replace location in apprun
  become: yes
  replace:
    path: "{{ repo_location_apprun }}/{{ apprun_name }}"
    replace: "{{ repo_location_apprun }}"
    regexp: 'REPO_HOME'
- name: Replace vars in apprun
  become: no
  lineinfile:
    path: "{{ repo_location_apprun }}/{{ apprun_name }}"
    regexp: '^export {{ item.name }}.*$'
    line: "export {{ item.name }}={{ item.value }}"
  with_items:
    - { name: "JIRA_USER", value: "{{ jira_username }}" }
    - { name: "JIRA_PASS", value: "{{ jira_password }}" }
    - { name: "MODE_USER", value: "{{ mode_user_firmware }}" }
    - { name: "MODE_PASS", value: "{{ mode_password_firmware }}" }
