---
- include_vars: "vars/all.yml"
#create user account, extracting usernames from the list of files in ./files 
- name: Create User Accounts
  become: yes
  user: name={{ item | basename }} shell=/bin/bash append=yes state=present
  with_fileglob:
    - users/*

- name: Add ssh keys
  become: yes
  authorized_key: user={{ item | basename }} key="{{ lookup('file', item )}}"
  with_fileglob:
    - users/*

- name: restart sshd
  become: yes
  service: name=ssh state=restarted
